server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://221.168.38.224/user?serverTimezone=Asia/Seoul
    username: root
    password: root
    
  devtools:
    livereload:
      port: 35730
    
  jpa:
    open-in-view: true  #default true 
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    
    show-sql: true
    properties:
      hibernate.format_sql: true


  jackson:
    serialization:
      fail-on-empty-beans: false
      
      
      
      
      